x-common: &common
  security_opt:
    - no-new-privileges:true
  environment: &commonenv
    TZ: ${TZ:-UTC}
    UMASK: "022"
    PUID: 1000  # Replace with your user ID (run 'id -u theo' to get it)
    PGID: 1000  # Replace with your group ID (run 'id -g theo' to get it)
  restart: unless-stopped
  networks:
    - media_network

volumes:
  portainer_data:
  traefik_data:

services:
  traefik:
    <<: *common
    container_name: traefik
    image: traefik:v2.10
    security_opt:
      - no-new-privileges:true
    command:
      - --api.dashboard=true
      - --api.insecure=true
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --entrypoints.web.address=:80
      - --log.level=DEBUG
      - --providers.docker.network=media_network
      - --serversTransport.insecureSkipVerify=true
    ports:
      - "${TRAEFIK_PORT:-80}:80"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - traefik_data:/letsencrypt
    labels:
      - traefik.enable=true
      - "traefik.http.routers.api.rule=Host(`${DOMAIN:-localhost}`) && (PathPrefix(`/`) || PathPrefix(`/api`))"
      - traefik.http.routers.api.service=api@internal
      - traefik.http.routers.api.priority=1
      - com.centurylinklabs.watchtower.scope=mediastack

  portainer:
    <<: *common
    container_name: portainer
    image: portainer/portainer-ce:latest
    command: -H unix:///var/run/docker.sock
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - portainer_data:/data
    labels:
      - traefik.enable=true
      - traefik.http.routers.portainer.rule=Host(`portainer.${DOMAIN:-localhost}`)
      - traefik.http.services.portainer.loadbalancer.server.port=9000
      - com.centurylinklabs.watchtower.scope=mediastack

  plex:
    <<: *common
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    ports:
      - 32400:32400
      - 32400:32400/udp
    environment:
      <<: *commonenv
      VERSION: docker
      PLEX_CLAIM: ${PLEX_CLAIM}
    volumes:
      - ${CONFIG_ROOT}/plex:/config
      - ${STORAGE_ROOT}/MOVIES:${MOVIES_PATH}:ro
      - ${STORAGE_ROOT}/SERIES:${SERIES_PATH}:ro
      - ${STORAGE_ROOT}/AUDIO:${MUSIC_PATH}:ro
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.plex.rule=Host(`plex.${DOMAIN:-localhost}`)
      - traefik.http.services.plex.loadbalancer.server.port=32400
      - com.centurylinklabs.watchtower.scope=mediastack

  sonarr:
    <<: *common
    container_name: sonarr
    image: linuxserver/sonarr:latest
    environment:
      <<: *commonenv
    volumes:
      - ${CONFIG_ROOT}/sonarr:/config
      - ${STORAGE_ROOT}/SERIES:${SERIES_PATH}
      - ${STORAGE_ROOT}/TORRENTS/COMPLETE:${DOWNLOADS_PATH}/complete:ro
    labels:
      - traefik.enable=true
      - traefik.http.routers.sonarr.rule=Host(`sonarr.${DOMAIN:-localhost}`)
      - traefik.http.services.sonarr.loadbalancer.server.port=8989
      - com.centurylinklabs.watchtower.scope=mediastack

  radarr:
    <<: *common
    container_name: radarr
    image: linuxserver/radarr:latest
    environment:
      <<: *commonenv
    volumes:
      - ${CONFIG_ROOT}/radarr:/config
      - ${STORAGE_ROOT}/MOVIES:${MOVIES_PATH}
      - ${STORAGE_ROOT}/TORRENTS/COMPLETE:${DOWNLOADS_PATH}/complete:ro
    labels:
      - traefik.enable=true
      - traefik.http.routers.radarr.rule=Host(`radarr.${DOMAIN:-localhost}`)
      - traefik.http.services.radarr.loadbalancer.server.port=7878
      - com.centurylinklabs.watchtower.scope=mediastack

  lidarr:
    <<: *common
    container_name: lidarr
    image: linuxserver/lidarr:latest
    environment:
      <<: *commonenv
    volumes:
      - ${CONFIG_ROOT}/lidarr:/config
      - ${STORAGE_ROOT}/AUDIO:${MUSIC_PATH}
      - ${STORAGE_ROOT}/TORRENTS/COMPLETE:${DOWNLOADS_PATH}/complete:ro
    labels:
      - traefik.enable=true
      - traefik.http.routers.lidarr.rule=Host(`lidarr.${DOMAIN:-localhost}`)
      - traefik.http.services.lidarr.loadbalancer.server.port=8686
      - com.centurylinklabs.watchtower.scope=mediastack

  organizr:
    <<: *common
    container_name: organizr
    image: organizr/organizr:latest
    environment:
      <<: *commonenv
    volumes:
      - ${CONFIG_ROOT}/organizr:/config
    labels:
      - traefik.enable=true
      - traefik.http.routers.organizr.rule=Host(`organizr.${DOMAIN:-localhost}`)
      - traefik.http.services.organizr.loadbalancer.server.port=80
      - com.centurylinklabs.watchtower.scope=mediastack

  calibre:
    <<: *common
    container_name: calibre
    image: linuxserver/calibre-web:latest
    environment:
      <<: *commonenv
    volumes:
      - ${CONFIG_ROOT}/calibre:/config
      - ${STORAGE_ROOT}/BOOKS:${BOOKS_PATH}
    labels:
      - traefik.enable=true
      - traefik.http.routers.calibre.rule=Host(`calibre.${DOMAIN:-localhost}`)
      - traefik.http.services.calibre.loadbalancer.server.port=8083
      - com.centurylinklabs.watchtower.scope=mediastack

  readarr:
    <<: *common
    container_name: readarr
    image: linuxserver/readarr:develop
    environment:
      <<: *commonenv
    volumes:
      - ${CONFIG_ROOT}/readarr:/config
      - ${STORAGE_ROOT}/BOOKS:${BOOKS_PATH}
      - ${STORAGE_ROOT}/TORRENTS/COMPLETE:${DOWNLOADS_PATH}/complete:ro
    labels:
      - traefik.enable=true
      - traefik.http.routers.readarr.rule=Host(`readarr.${DOMAIN:-localhost}`)
      - traefik.http.services.readarr.loadbalancer.server.port=8787
      - com.centurylinklabs.watchtower.scope=mediastack

  prowlarr:
    <<: *common
    container_name: prowlarr
    image: linuxserver/prowlarr:latest
    environment:
      <<: *commonenv
    volumes:
      - ${CONFIG_ROOT}/prowlarr:/config
    labels:
      - traefik.enable=true
      - traefik.http.routers.prowlarr.rule=Host(`prowlarr.${DOMAIN:-localhost}`)
      - traefik.http.services.prowlarr.loadbalancer.server.port=9696
      - com.centurylinklabs.watchtower.scope=mediastack

  qbittorrent:
    <<: *common
    container_name: qbittorrent
    image: linuxserver/qbittorrent:latest
    environment:
      <<: *commonenv
      WEBUI_PORT: 8080
    volumes:
      - ${CONFIG_ROOT}/qbittorrent:/config
      - ${STORAGE_ROOT}/TORRENTS:${DOWNLOADS_PATH}
    ports:
      - 6881:6881
      - 6881:6881/udp
    labels:
      - traefik.enable=true
      - traefik.http.routers.qbittorrent.rule=Host(`qbittorrent.${DOMAIN:-localhost}`)
      - traefik.http.services.qbittorrent.loadbalancer.server.port=8080
      - com.centurylinklabs.watchtower.scope=mediastack

  overseerr:
    <<: *common
    container_name: overseerr
    image: sctx/overseerr:latest
    ports:
      - 5055:5055
      - 5055:5055/udp
    environment:
      <<: *commonenv
    volumes:
      - ${CONFIG_ROOT}/overseerr:/app/config
    labels:
      - traefik.enable=true
      - traefik.http.routers.overseerr.rule=Host(`overseerr.${DOMAIN:-localhost}`)
      - traefik.http.services.overseerr.loadbalancer.server.port=5055
      - com.centurylinklabs.watchtower.scope=mediastack

  bazarr:
    <<: *common
    container_name: bazarr
    image: linuxserver/bazarr:latest
    environment:
      <<: *commonenv
    volumes:
      - ${CONFIG_ROOT}/bazarr:/config
      - ${STORAGE_ROOT}/SERIES:${SERIES_PATH}:ro
      - ${STORAGE_ROOT}/MOVIES:${MOVIES_PATH}:ro
    labels:
      - traefik.enable=true
      - traefik.http.routers.bazarr.rule=Host(`bazarr.${DOMAIN:-localhost}`)
      - traefik.http.services.bazarr.loadbalancer.server.port=6767
      - com.centurylinklabs.watchtower.scope=mediastack

  recyclarr:
    <<: *common
    container_name: recyclarr
    image: recyclarr/recyclarr:latest
    environment:
      <<: *commonenv
    volumes:
      - ${CONFIG_ROOT}/recyclarr:/config
    labels:
      - com.centurylinklabs.watchtower.scope=mediastack

  flaresolverr:
    <<: *common
    container_name: flaresolverr
    image: ghcr.io/flaresolverr/flaresolverr:latest
    environment:
      LOG_LEVEL: info
      TZ: ${TZ:-UTC}
    labels:
      - traefik.enable=true
      - traefik.http.routers.flaresolverr.rule=Host(`flaresolverr.${DOMAIN:-localhost}`)
      - traefik.http.services.flaresolverr.loadbalancer.server.port=8191
      - com.centurylinklabs.watchtower.scope=mediastack

  homarr:
    <<: *common
    container_name: homarr
    image: ghcr.io/ajnart/homarr:latest
    environment:
      <<: *commonenv
    volumes:
      - ${CONFIG_ROOT}/homarr:/app/data
      - ${CONFIG_ROOT}/homarr/icons:/app/public/icons
    labels:
      - traefik.enable=true
      - traefik.http.routers.homarr.rule=Host(`homarr.${DOMAIN:-localhost}`)
      - traefik.http.services.homarr.loadbalancer.server.port=7575
      - com.centurylinklabs.watchtower.scope=mediastack

  deleterr:
    <<: *common
    container_name: deleterr
    image: ghcr.io/rfsbraz/deleterr:latest
    environment:
      <<: *commonenv
    volumes:
      - ${CONFIG_ROOT}/deleterr:/config
      - ${STORAGE_ROOT}/SERIES:${SERIES_PATH}:ro
      - ${STORAGE_ROOT}/MOVIES:${MOVIES_PATH}:ro
      - ${STORAGE_ROOT}/TORRENTS/COMPLETE:${DOWNLOADS_PATH}/complete:ro
    labels:
      - traefik.enable=true
      - traefik.http.routers.deleterr.rule=Host(`deleterr.${DOMAIN:-localhost}`)
      - traefik.http.services.deleterr.loadbalancer.server.port=7474
      - com.centurylinklabs.watchtower.scope=mediastack

  watchtower:
    <<: *common
    container_name: watchtower
    image: containrrr/watchtower:latest
    environment:
      TZ: ${TZ:-UTC}
      WATCHTOWER_CLEANUP: "true"
      WATCHTOWER_SCHEDULE: "0 0 4 * * *"
      WATCHTOWER_INCLUDE_STOPPED: "false"
      WATCHTOWER_MONITOR_ONLY: "false"
      WATCHTOWER_SCOPE: mediastack
      WATCHTOWER_DEBUG: ${WATCHTOWER_DEBUG:-false}
      WATCHTOWER_NOTIFICATION_REPORT: ${WATCHTOWER_NOTIFICATION_REPORT:-false}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    labels:
      - com.centurylinklabs.watchtower.scope=mediastack

networks:
  media_network:
    name: media_network
